fail-fast: true
repos:
- repo: https://github.com/pocc/pre-commit-hooks
  rev: master
  hooks:
    - id: clang-format
      args: [--style=Google]
    - id: clang-tidy
    - id: cppcheck
    - id: cpplint
    - id: include-what-you-use
