#define ESTHER_VERSION 0.1.0

#define CMAKE_SYSTEM Darwin-20.3.0
#define CMAKE_SYSTEM_NAME Darwin
#define CMAKE_SYSTEM_VERSION 20.3.0
#define CMAKE_HOST_SYSTEM_NAME Darwin
#define CMAKE_SYSTEM_PROCESSOR arm64

#define SDL2_PACKAGE_VERSION 2.26.5
#define SPDLOG_PACKAGE_VERSION 1.11.0
#define SDL2_TTF_PACKAGE_VERSION 2.20.1
#define SDL2_IMAGE_PACKAGE_VERSION 2.6.2
#define SDL2_MIXER_PACKAGE_VERSION 2.6.2

#define CMAKE_EXPORT_COMPILE_COMMANDS TRUE

#define CMAKE_BUILD_TYPE Debug
#define CMAKE_BUILD_TYPE_RELEASE Release
#if CMAKE_BUILD_TYPE == CMAKE_BUILD_TYPE_RELEASE
#define RELEASE_BUILD 1
#endif
